#! /usr/bin/env python

top = '..'

def build(bld):
    bld.program(
        source = 'test.c',
        target = 'test_recontext',
        use    = 'recontext',
        rpath  = bld.top_dir + '/build/src',
        install_path = None,
    )
